### ISSUE TITLE
adding comments doesn't work

### ISSUE THREAD

**Issue by elliniyessine** [AymenKoched/Projet-PHP#2]
[::1]:49582 [500]: POST /addCommentProcess.php - Uncaught PDOException: SQLSTATE[HY000]: General error: 1364
Field 'nom' doesn't have a default value in /home/elliniyessine/Projet-PHP/Repository.php:55
Stack trace:
#0 /home/elliniyessine/Projet-PHP/Repository.php(55): PDOStatement->execute()
#1 /home/elliniyessine/Projet-PHP/addCommentProcess.php(4): Repository->Create()
#2 {main}
  thrown in /home/elliniyessine/Projet-PHP/Repository.php on line 55

**Comment by elliniyessine** [comment]
Was an issue with my database tables' definition
